### ISSUE TITLE
Trouble with running FlakeFlagger

### ISSUE THREAD

**Issue by alperen21** [AlshammariA/FlakeFlagger#3]
Hello,

I am trying to use test-feature-collector to detect test flakiness on a maven project.

I have cloned your repository to my machine and ran "mvn clean install" on test-feature-collector, then copied test-smells-maven-extension-1.0-SNAPSHOT.jar to /Users/alperenyildiz/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3/lib/ext/ 

Then, went to the maven repository I am trying to analyze and ran "mvn verify" on it couple times; then I investigated target/test-classes and target/classes folders and subfolders beneath them but I could not find smells.csv file. Thus, I suspected that something is wrong with my setup or I am using your tool incorrectly and wanted to ask for your assistance. Any help would be much appreciated.

Thank you,

**Comment by jon-bell** [comment]
Hi,
The output of the test feature detector will be the list of features that are detected on each test, and not a list of flaky tests. Can you share the entire build output from running `mvn -V verify`? Can you share the project that you are testing?

Best,
Jon

**Comment by alperen21** [comment]
Hello, 

Thank you for your reply. 

I have created a dummy maven project with flakiness and I am sharing the project with you as a zip file alongside with failing and passing mvn -V verify outputs.

[verifyPass.log](https://github.com/AlshammariA/FlakeFlagger/files/7467013/verifyPass.log)
[verifyFail.log](https://github.com/AlshammariA/FlakeFlagger/files/7467016/verifyFail.log)
[demo.zip](https://github.com/AlshammariA/FlakeFlagger/files/7467019/demo.zip)

.

**Comment by jon-bell** [comment]
@alperen21 - your maven log shows that your Maven Home folder is `/usr/local/Cellar/maven/3.8.1/libexec`. If you want to use the feature detector on every maven project that you build, then you would need to copy it to `/usr/local/Cellar/maven/3.8.1/libexec/lib/ext`. Alternatively (what I would suggest), you could download a copy of Maven, place it in some location like `~/maven-with-feature-detector/`, copy the extension to `~/maven-with-feature-detector/lib/ext/` and then, when you want to run maven with the feature detector, run `~/maven-with-feature-detector/bin/mvn`. The `Maven home` line at the start of the output from `mvn -V verify` should reflect the copy of maven that you are running.


I've attached the [output that I obtained](https://github.com/AlshammariA/FlakeFlagger/files/7467566/demo-smells-and-demographics-reports.zip) when running the feature detector on your demo project.

**Comment by alperen21** [comment]
With your suggestion I was able to run FlakeFlagger. Thank you so much for your assistance.
